twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/assets/styles': styles
        '%kernel.project_dir%/public/imgs': images

when@test:
    twig:
        strict_variables: true
