webhook:
    resource: '@FrameworkBundle/Resources/config/routing/webhook.xml'
    prefix: /webhook
framework:
    webhook:
        routing:
            mailtrap: mailer.webhook.request_parser.mailtrap